### PR TITLE
Remove MessageFactory

### PR DESCRIPTION
**Pull request by ddeboer**
As MessageFactory is now in a separate package. Also remove dependency on phly/http.

### CODE REVIEW

**Comment by ddeboer** [comment]
See also https://github.com/php-http/adapter/issues/22.

**Comment by sagikazarmark** [comment]
Sorry, that separation is meant for the interface, not the actual implementation.

Currently I am separating the main project into four parts:
1. Adapter interfaces
2. Internal interfaces
3. Common (implementations of adapter and other commonly used interfaces)
4. Core every other implementations that are usually used internally (eg. internal request)

If you look at the core package (internal_separation branch) you can see that the message factory here is currently used by the core's extension.

I know it is a bit messy right now, but I haven't been able to finish the separation completely because we couldn't discuss some things with @egeloen

**Comment by sagikazarmark** [comment]
If you take a look at the message-factory package, you can see that it is an interface package for PSR7 messages. Basically the interfaces for construction logic that is missing from the PSR.

**Comment by ddeboer** [comment]
I see. I’d suggest to keep things simple. I’m trying to work on a Guzzle 6 adapter, but ended up it dependency conflict hell. :confounded: 

Anything I can do to help?

**Comment by sagikazarmark** [comment]
What dependency conflict exactly? Is it because the psr message version? If so, I am going to replace phly/http with the package mentioned by you. Since the API seems to be the same, it should not be a problem. That should solve the conflict IMO.

**Comment by ddeboer** [comment]
Yeah, switching to psr/http-message 1.0 everywhere resolved the conflict. I’ll keep you posted. :wink:

**Comment by sagikazarmark** [comment]
Conflict should now be resolved, phly/http is replaced with diactoros

**Pull request closed without merging**
